version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    labels:
      - 'pr: dependencies'
    versioning-strategy: increase
    groups:
      development-dependencies:
        dependency-type: development
        exclude-patterns: ['remark-*']
    cooldown:
      default-days: 7

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    labels:
      - 'pr: dependencies'
    cooldown:
      default-days: 7
