version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    labels:
      - 'pr: dependencies'
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    labels:
      - 'pr: dependencies'
