name: CI

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  lint:
    uses: stylelint/.github/.github/workflows/call-lint.yml@ab7979355590956aa96d306dedfda6b2d42c4982 # 1.1.0
    with:
      node-version-file: .nvmrc
    permissions:
      contents: read

  test:
    uses: stylelint/.github/.github/workflows/call-test.yml@ab7979355590956aa96d306dedfda6b2d42c4982 # 1.1.0
    with:
      node-version-file: .nvmrc
    permissions:
      contents: read

  build:
    needs: test
    runs-on: ubuntu-slim
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ case(github.event.pull_request.head.repo.full_name == github.repository, github.event.pull_request.head.ref, github.sha) }}
          persist-credentials: false # Prevent build-time code from accessing the checkout credentials.
      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install latest npm
        run: npm install --global npm@latest
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Detect changes
        id: changes
        run: |
          if ! git diff --quiet -- dist/; then
            echo "changed=true" >> "${GITHUB_OUTPUT}"
            if [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
              echo "::error::Run build and commit."
              exit 1
            fi
          fi
      - name: Commit and push
        if: ${{ github.event_name == 'pull_request' && steps.changes.outputs.changed && github.event.pull_request.head.repo.full_name == github.repository }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PR_BRANCH: ${{ github.event.pull_request.head.ref }}
        run: |
          git config --local user.name "${GITHUB_ACTOR}"
          git config --local user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git add dist/
          git commit -m 'Build dist'
          gh auth setup-git
          git push origin "HEAD:${PR_BRANCH}"

  dependency-review:
    if: ${{ github.event_name == 'pull_request' }}
    uses: stylelint/.github/.github/workflows/call-dependency-review.yml@ab7979355590956aa96d306dedfda6b2d42c4982 # 1.1.0
    permissions:
      contents: read
