name: Test

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  get-node-version:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    outputs:
      version: ${{ steps.node-version.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Get Node.js version from package.json
        id: node-version
        shell: bash
        run: echo "value=$(jq -r '.engines.node' package.json)" >> "${GITHUB_OUTPUT}"

  lint:
    needs: get-node-version
    uses: stylelint/.github/.github/workflows/call-lint.yml@60889da59f384526b8185d2aa85b35620aa6bcc0 # 0.6.0
    with:
      node-version: ${{ needs.get-node-version.outputs.version }}
    permissions:
      contents: read

  test:
    needs: get-node-version
    uses: stylelint/.github/.github/workflows/call-test.yml@60889da59f384526b8185d2aa85b35620aa6bcc0 # 0.6.0
    with:
      node-version: '["${{ needs.get-node-version.outputs.version}}"]'
    permissions:
      contents: read
